package multithreading;

/**
 *
 * @Sir Darey
 * 
 * Synchronization helps to restrict multiple threads from operating simultaneously on an object or a variable 
 * 
 * Types of Synchronization
 * 
 * 1. SynchronizedMethod
 * 2. Synchronized Block
 * 3. Static Synchronization
 */
class Brackets {
    
    //Static Synchronization is used with the static keyword in a function or method
    synchronized public static void generate (String threadName) { 
        for (int i=1; i<=10; i++) {
            if (i<=5)
                System.out.print("[");
            else
                System.out.print("]");
        }
        System.out.println("Generated by: "+threadName);
    }
}

public class _7_StaticSynchronization {
    
    public static void main(String[] args) throws InterruptedException{        
        new Thread(()-> { 
            for (int i=0; i<5; i++) 
                Brackets.generate("Thread 1");
        }).start();
        
        new Thread(()-> {   
            for (int i=0; i<5; i++) 
                Brackets.generate("Thread 2");
        }).start();
    }
}
